name: Tests

on:
  push:
    branches: ["development"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies for testing
        run: |
          python -m pip install --upgrade pip
          pip install fluxional[all] pytest mypy ruff 

      - name: Run tests
        run: |
          pytest -v
          mypy fluxional/
          ruff fluxional/ --no-cache
